### ISSUE TITLE
How does one interpret an unhelpful message "row not found" pertaining to a signer trying to pay for gas during deployment with a testnet account.

### ISSUE THREAD

**Issue by severian1778** [kadena-io/pact-lang-api#40]
I am trying to write a client for deploying pact smart contracts and I send in the following to the send endpoint.

```
%{
  envData: %{
    marketKeyset: ["AB8B50BE159BE05D97482BD1DBF73899A348BB1A5DD9BBECED8891E4918E1EA4"],
    upgrade: false
  },
  keyPairs: [
    %{
      publicKey: "AB8B50BE159BE05D97482BD1DBF73899A348BB1A5DD9BBECED8891E4918E1EA4",
      secretKey: "9669358B68A2229F3F7F962684E5A6497CE72355603359AE1C0DED113DA77DB1"
    }
  ],
  meta: %{
    chainId: "1",
    creationTime: 1658801266,
    gasLimit: 65000,
    gasPrice: 1.0e-6,
    sender: "AB8B50BE159BE05D97482BD1DBF73899A348BB1A5DD9BBECED8891E4918E1EA4",
    ttl: 28000
  },
  networkId: "testnet04",
  pactCode:  <Some code>.

```

In return,  I receive the following error message in the body:

`body: "Validation failed for hash \"-UraBAOPEXrTq3qe0UbblIesG0Kjdv60LPwiFs3LbEc\": Attempt to buy gas failed with: : Failure: Tx Failed: read: row not found: AB8B50BE159BE05D97482BD1DBF73899A348BB1A5DD9BBECED8891E4918E1EA4",`

The wallet keys are associated with a spot-generated chainweaver wallet with public and private keys via pact -g and the wallet has currency in it via the faucet.

Any guidance on the issue here?   

[edit]:  How do we make this cmd pass w.r.t the issues around buying gas from the sender account which clearly exists?   Some have said we have to add a gas capability to the keyset.  Please point to another issue or tutorial example with clean and clear instructions on how to avoid this error?

**Comment by mightybyte** [comment]
> How do we make this cmd pass w.r.t the issues around buying gas from the sender account which clearly exists?

The sender account `AB8B50BE159BE05D97482BD1DBF73899A348BB1A5DD9BBECED8891E4918E1EA4` actually does not exist as can be seen [here](https://balance.chainweb.com/?server=api.testnet.chainweb.com&account=AB8B50BE159BE05D97482BD1DBF73899A348BB1A5DD9BBECED8891E4918E1EA4).  The account that does exist is `k:ab8b50be159be05d97482bd1dbf73899a348bb1a5dd9bbeced8891e4918e1ea4` (see [here](https://balance.chainweb.com/?server=api.testnet.chainweb.com&account=k:ab8b50be159be05d97482bd1dbf73899a348bb1a5dd9bbeced8891e4918e1ea4)).

**Comment by severian1778** [comment]
Good that is clear -> Yes as we mentioned on Kadena Builders Telegram,  correcting this issue by adding k: to the signer leads to:

body: "Validation failed for hash \"Hb0WGLQU84csawWcSBbp7ubO3s1Py09NdShP1lA5EdI\": Attempt to buy gas failed with: : Failure: Tx Failed: Keyset failure (keys-all): [ab8b50be...]",

In the 2019 blog post by Emily Pillmore, she said that signers are simply public keys so this seems to have changed since 2019.  Also, in the voting dapp, it isn't clear that you have to use a k: account address as a signer.   Now that we have affirmed that you have to use a k: account and eliminated one of the possibilities, how would you correct the request given in OP with a k: added to the signer?   

aka:  Why is the keyset failing?

**Comment by mightybyte** [comment]
This forum is for issues with the pact-lang-api library, not generic tech support.  Please don't scatter your requests across every different social media platform and expect people in one place to read things you've asked in another place.
